[openai]
API_KEY = "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"
BASE_URL = "https://openrouter.ai/api/v1"
